services:
  - type: web
    name: epub-simplifier
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.main:app
    autoDeploy: true
